verdie-g/crpg

- src/WebUI/src/assets/themes/oruga-tailwind/components/table.css
- src/WebUI/src/components/character/inventory/CharacterInventoryDollSlot.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryItemCard.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryItemDetail.vue
closed https://github.com/verdie-g/crpg/issues/819
@verdie-g looks like a hotfix
> webui: steam-browser-css

- src/Module.Server/Balancing/MatchBalancer.cs
> avoid swapping when not needed

- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/__mocks__/constants.json
- src/WebUI/src/__mocks__/i18n.ts
- src/WebUI/src/components/character/inventory/CharacterInventoryDoll.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryDollSlot.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryItemCard.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryItemDetail.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryItemList.vue
- src/WebUI/src/composables/character/use-inventory-dnd.spec.ts
- src/WebUI/src/composables/character/use-inventory-dnd.ts
- src/WebUI/src/models/item.ts
- src/WebUI/src/pages/characters/[id]/index.vue
- src/WebUI/src/services/characters-service.spec.ts
- src/WebUI/src/services/characters-service.ts
- src/WebUI/src/services/item-search-service/aggregations.ts
- src/WebUI/src/services/item-service.spec.ts
- src/WebUI/src/services/item-service.ts
- when trying to equip
- shop
- inventory
- automatic unequip items with a requirement, when `respec, retire or setTournament`
> webui: explain-strength-requirement

- src/WebUI/src/layouts/default.vue
- src/WebUI/src/pages/characters.vue
- src/WebUI/src/pages/characters/[id].vue
> webui: move-character-builder-btn

- src/WebUI/src/composables/use-sticky-sidebar.ts
- src/WebUI/src/pages/characters/[id]/inventory.vue
if possible, can this be released as a hotfix?
I'm sorry, I missed something
> webui: sticky-aside-hotfix

- src/Module.Server/Balancing/MatchBalancer.cs
- src/Module.Server/Balancing/WeightHelpers.cs
Fixed isSwapValid for clangroups not taking in account clan group penalty
Fixed IsWeightRatioAcceptable not taking in account clan group penalty
> Mod : Fixed 2 bugs in bannerbalancing

- src/WebUI/src/services/characters-service.spec.ts
- src/WebUI/src/services/characters-service.ts
stacked weapons did not take in account stackAmount in weapons-array when calculating weight.
annotation:
unit test only tests for type checks & stack calculation, not for 'if horse harnesses and mounts are exempt from calculation'
> fixed weight calculation for stackable weapons and added improvable unit test 

- src/WebUI/src/components/app/OnlinePlayers.spec.ts
- src/WebUI/src/components/app/OnlinePlayers.vue
- src/WebUI/src/composables/use-game-server-stats.spec.ts
- src/WebUI/src/composables/use-game-server-stats.ts
- src/WebUI/src/composables/use-poll-interval.ts
- src/WebUI/src/layouts/default.vue
- src/WebUI/src/pages/characters/[id].vue
- src/WebUI/src/services/game-server-statistics-service.spec.ts
sorry for premature PR earlier, missed default.vue indicator.
also improved logic and null-checks in OnlinePlayers.vue + added some unit-tests
> 895 avoid printing 0 online players on error

- src/Module.Server/Rewards/CrpgRewardServer.cs
I lost gold while trying to start a server. You're already chasing after bots alone for a while, not having multiplier, if you also have  to change your equipment to not lose gold , the deal is awful.
> mod : Low pop upkeep 50%-> 20%

- src/WebUI/src/composables/use-sticky-sidebar.spec.ts
- src/WebUI/src/composables/use-sticky-sidebar.ts
- src/WebUI/src/pages/characters/[id]/inventory.vue
- src/WebUI/vite.config.ts
this task again, I beg your pardon
I wrote tests and made a [mockup ](https://github.com/verdie-g/crpg/issues/873#issuecomment-1520919567) of how it works
> webui: inventory-filter-sticky-sidebar-unit-fix

- src/WebUI/src/components/character/inventory/CharacterInventoryFilter.vue
- src/WebUI/src/components/shop/ShopItemTypeSelect.vue
- src/WebUI/src/services/item-search-service/index.ts
support for the new version of the [@types/itemsjs](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65018/files#diff-28f6473ee2748d989f509b2affb30a94f27939d073393c88785442635a5bd0bbR84)
> webui: itemsjs fix ts

- src/WebUI/src/services/item-search-service/aggregations.ts
added missing props in frontend aggregation to show thust speed and dmg for maces (found by using warhammer)
PS:
VERY HARD TASK, ty orle :D ;)
> added missing aggregation props

- Crpg.sln
- src/Launcher/Launcher.csproj
- src/Module.Client/Module.Client.csproj
- src/Module.Server/Module.Server.csproj
- test/Module.UTest/Module.UTest.csproj
> mod : Removed all warning in the project.

- src/WebUI/src/components/app/HHTooltip.vue
- src/WebUI/src/components/ui/ClosableTooltip.vue
- src/WebUI/src/pages/characters/[id]/inventory.vue
> webui: fix-modal-close-brn-position

- src/WebUI/src/middlewares/clan.spec.ts
- src/WebUI/src/middlewares/clan.ts
- src/WebUI/src/pages/clans/[id]/index.spec.ts
- src/WebUI/src/pages/clans/[id]/index.vue
- src/WebUI/src/pages/clans/[id]/update.spec.ts
- src/WebUI/src/pages/clans/[id]/update.vue
- src/WebUI/src/pages/clans/create.spec.ts
- src/WebUI/src/pages/clans/create.vue
- src/WebUI/src/stores/user.ts
- fixes this: https://discord.com/channels/279063743839862805/761283333840699392/1103634770946179102
- we broke that in this PR https://github.com/verdie-g/crpg/pull/934
> webui: fix errors when working with clan

- src/WebUI/src/boot/router.ts
- src/WebUI/src/middlewares/clan.ts
- src/WebUI/src/models/user.ts
- src/WebUI/src/pages/clans/[id]/applications.vue
- src/WebUI/src/pages/clans/[id]/index.vue
- src/WebUI/src/pages/clans/[id]/update.vue
- src/WebUI/src/services/clan-service.spec.ts
- src/WebUI/src/services/clan-service.ts
- src/WebUI/src/types/vue-router.d.ts
- add route guards for `clan/{id}/applications` and `clan/{id}/update` pages, check if you do not have the valid clan role
> webui: route guards for clan page

- src/WebUI/src/components/clan/ClanForm.spec.ts
- src/WebUI/src/components/clan/ClanForm.vue
- src/WebUI/src/composables/clan/use-clan-applications.spec.ts
- src/WebUI/src/composables/clan/use-clan.spec.ts
- src/WebUI/src/middlewares/clan.spec.ts
- src/WebUI/src/pages/clans/[id]/applications.spec.ts
- src/WebUI/src/pages/clans/[id]/index.spec.ts
- src/WebUI/src/pages/clans/[id]/update.spec.ts
- src/WebUI/src/pages/clans/create.spec.ts
- src/WebUI/src/pages/clans/index.spec.ts
- src/WebUI/src/services/clan-service.spec.ts
- src/WebUI/src/stores/user.spec.ts
only unit tests, I will add later for other modules
> webui: fix clan units

- src/WebUI/src/pages/privacy-policy.vue
> webui: add contact privacy policy

- src/WebUI/src/pages/characters/[id]/index.vue
Update the Lorem Ipsums for the Virtual Tour to fit actual descriptions of each item (Experience, Exp. Multiplier etc etc.)
Updated descriptions for: 
Level
Experience
Experience Multiplier
Generation
Respecialize
Retire
Tournament
This change replaces the Lorem Ipsum placeholders with custom-descriptions of each title for the purpose of fleshing out the Virtual Tour, as requested by orle.
> webUI: Update Lorem Ipsum placeholder texts for Onboarding

- data/constants.json
- src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
increased shield coverage for infantry.
> mod : shield take 25% more damage, increased shield coverage for inf

- src/WebUI/src/pages/characters/[id]/index.vue
forgot here https://github.com/verdie-g/crpg/pull/959
> webui: fix missed refactoring

- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/assets/themes/oruga-tailwind/components/dropdown.css
- src/WebUI/src/pages/characters/[id]/index.vue
- src/WebUI/src/services/characters-service.spec.ts
- src/WebUI/src/services/characters-service.ts
- src/WebUI/src/utils/array.spec.ts
- src/WebUI/src/utils/array.ts
issue https://discord.com/channels/279063743839862805/761283333840699392/1106951473591488542
> webui: retire type + reward table

- src/WebUI/src/__mocks__/user-items.json
- src/WebUI/src/__mocks__/user-rare-items.json
- src/WebUI/src/components/character/inventory/CharacterInventoryDoll.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryDollSlot.spec.ts
- src/WebUI/src/components/character/inventory/CharacterInventoryDollSlot.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryFilter.spec.ts
- src/WebUI/src/components/character/inventory/CharacterInventoryItemCard.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryItemList.vue
- src/WebUI/src/composables/character/use-inventory-dnd.spec.ts
- src/WebUI/src/composables/character/use-inventory-dnd.ts
- src/WebUI/src/models/user.ts
- src/WebUI/src/pages/characters/[id].vue
- src/WebUI/src/pages/characters/[id]/inventory.vue
- src/WebUI/src/pages/shop.spec.ts
- src/WebUI/src/pages/shop.vue
- src/WebUI/src/services/item-search-service/__tests__/helpers.spec.ts
- src/WebUI/src/services/item-search-service/__tests__/item-search-service.spec.ts
- src/WebUI/src/services/item-search-service/helpers.ts
- src/WebUI/src/services/item-search-service/index.ts
- src/WebUI/src/services/item-service.spec.ts
- src/WebUI/src/services/item-service.ts
- src/WebUI/src/services/users-service.spec.ts
- src/WebUI/src/services/users-service.ts
- src/WebUI/src/stores/user.ts
Related to this https://github.com/verdie-g/crpg/pull/998
After merging [this ](https://github.com/verdie-g/crpg/pull/1006) PR, I will rebase and update this PR
> webui: migrate baseitem to item

- src/WebUI/src/boot/router.ts
- src/WebUI/src/utils/router.spec.ts
- src/WebUI/src/utils/router.ts
The key change here is: https://github.com/verdie-g/crpg/pull/1024/files#diff-d14494a18f79d7a2ec7f9cfd170e3b3510f96d2e6b9c049bb250ef287049f488R29
fix this:
> webui: decode-search-query-fix

- src/WebUI/src/pages/index.vue
> webui: main-page-intro

- src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs
In order to reduce the power of hybrid , i made the first wpf points less impactful
> mod : swing speed tweak

- src/Application/Common/Services/ICharacterService.cs
- src/Application/Common/Services/IExperienceTable.cs
- src/Module.Server/Common/CrpgExperienceTable.cs
- test/Application.UTest/Common/Services/CharacterServiceTest.cs
> webapi : Retiring above level 31 does not make you lose Heirloom Points

- data/items.json
- src/Module.Server/ModuleData/items/horses_and_others.xml
- src/Module.Server/ModuleData/items/weapons.xml
Crossbow rework
Bow Rework
Horse patch
> mod : ItemPatch

- data/constants.json
> mod : buff ironflesh bonus from 3 to 4

- src/WebUI/src/components/character/inventory/CharacterInventoryItemList.vue
> webui: allow equip item with broken thumb

- src/WebUI/src/components/character/inventory/CharacterInventoryDoll.vue
> webui: unequip-item-with-broken-thumb

- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/components/app/Login.vue
> webui: login btn improve

- src/WebUI/src/services/item-search-service/aggregations.ts
> webui: add mount bodyLength

- src/WebUI/src/pages/shop.vue
> webui: improve pagination

- src/Application/System/Commands/SeedDataCommand.cs
- src/WebUI/src/components/moderator/RestrictionsTable.vue
- src/WebUI/src/components/user/UserMedia.vue
- src/WebUI/src/pages/leaderboard.vue
> webui: leaderboard table narrowed

- src/WebUI/src/components/competitive/RankTable.vue
https://discord.com/channels/279063743839862805/1088203928497303715/1123600889475760128
> webui: rating table reverse direction

- src/Module.Server/ModuleData/characters.xml
Unless intended, d7dc9552b4e2c52f3512aa08e9c420aa4e3f2b86 made the viscount naked. This PR replaces the armour to before that commit.
> mod: fix viscount armour

- src/Application/Characters/Queries/GetLeaderboardQuery.cs
- src/WebApi/Controllers/LeaderboardController.cs
- src/WebUI/src/pages/leaderboard.vue
- src/WebUI/src/services/leaderboard-service.spec.ts
- src/WebUI/src/services/leaderboard-service.ts
- test/Application.UTest/Characters/GetLeaderboardQueryTest.cs
> faet: leaderboard filter by char class

- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/components/character/inventory/CharacterInventoryItemDetail.vue
> webui: copy to clipboard item name

- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/components/character/inventory/CharacterInventoryDoll.vue
- src/WebUI/src/components/character/inventory/CharacterInventoryDollSlot.vue
- src/WebUI/src/services/characters-service.ts
> webui: improve extra weapon slot description

- src/WebUI/src/components/shop/ShopGridItemName.vue
> webui: isNew badge

- src/Module.Server/ModuleData/characters.xml
> mod: fix dtv recruit item id

- src/Module.Server/Modes/Dtv/CrpgDtvClient.cs
> mod: fix string typo

- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/components/shop/ShopGridFilter.vue
- src/WebUI/src/models/item.ts
- src/WebUI/src/services/item-search-service/aggregations.ts
- src/WebUI/src/services/item-search-service/indexator.ts
- src/WebUI/src/services/item-service.ts
> webui: filter by armor material type

- test/Application.UTest/Games/GetGameUserCommandTest.cs
Inspired by the already existing checkbotitem test
> mod : make starting item test human readable

- src/Module.Server/ModuleData/characters.xml
- src/Module.Server/ModuleData/class_divisions.xml
- src/Module.Server/ModuleData/dtv_data.xml
- Add new Aserai faction (thanks Arn)
- Add ranged ai skill to throwers
- Buff boss units
- Tweak existing bots
- Fix dwarf wave boss `count="1.0"`
- Add heavy cavalry to tincan round
> mod: Dtv bot improvements

- src/WebUI/src/pages/characters/[id]/inventory.vue
- src/WebUI/src/services/item-service.spec.ts
- src/WebUI/src/services/item-service.ts
[See](https://github.com/verdie-g/crpg/issues/1190)
> webui: unclassify shields

- src/WebUI/src/pages/characters/[id]/inventory.vue
https://discord.com/channels/279063743839862805/1088203928497303715/1131329786413854761
> webui: close detail onPress ESC

- src/WebUI/src/pages/characters/[id]/inventory.vue
https://discord.com/channels/279063743839862805/1088203928497303715/1132318093373362237
> webui: fix sorting by type in inventory

- src/Module.Server/ModuleData/Languages/CNs/std_native_strings_xml-zho-CN.xml
improve translate CN to make it more in line with Native translation styles
> mod: improve translate CN

- src/Module.Server/ModuleData/characters.xml
- Increase crpg_dtv_legion_centurion throwing WPF so they actually use their throwing weapons
> mod: fix dtv centurion not throwing pilum

- src/WebUI/src/components/app/ConfirmActionForm.vue
- src/WebUI/src/components/character/CharacterMedia.vue
- src/WebUI/src/components/character/CharacterSelectItem.vue
- src/WebUI/src/pages/characters.vue
- src/WebUI/src/pages/characters/[id]/index.vue
- src/WebUI/src/types/vite-components.d.ts
https://github.com/verdie-g/crpg/assets/33551334/5c55fc11-5166-42e3-98f0-3ac4d5df742c
> webui: improve retire confirmation
